import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [Activities1 , setActivities1] = useState("取得中");
  const [Activities2 , setActivities2] = useState("取得中");
  const [Activities3 , setActivities3] = useState("取得中");
  //useEffect
  useEffect(() => {
    getCo1().then(res => setActivities1(res));
    getCo2().then(res => setActivities2(res));
    getCo3().then(res => setActivities3(res));
  },[]);
  return (
    <>
      <Head>
        <title>Skota11&apos;s Service Status</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-center text-2xl mt-12 mb-4 text-osyare_black'>Skota11&apos;s Service Status</h1>
        <p className='my-8 text-center text-xl text-osyare_black'><a href="https://skota11.com" target="_blank" rel="noopener noreferrer">Website</a> | <a href="https://github.com/Skota11" target="_blank" rel="noopener noreferrer">Github</a></p>
      <div className='flex place-content-center my-8'>
            <div className='rounded-xl w-4/5 bg-picton_blue max-w-screen-sm p-8 shadow-lg duration-300 hover:shadow-2xl'>
              <h2 className='my-4 text-xl text-osyare_black'>こたすき～ / KotaSkey</h2>
                <div>
                  <a className='underline text-osyare_black' href="https://mi.skota11.com">こたすき～ / KotaSkey</a>
                  <p className='text-osyare_black'>Misskeyサーバーです</p>
                  <p><a href="https://stats.uptimerobot.com/0Bny6Uk3vq/793949437" target="_blank" rel="noopener noreferrer">UpTimeRobot</a></p>
                </div>
                <hr className='my-4' />
                <h2 className='my-2 text-xl text-osyare_black'>Status</h2>
                <p className='text-osyare_black'>{Activities1}</p>
              </div>
            </div>
            <div className='flex place-content-center my-8'>
            <div className='rounded-xl w-4/5 bg-st_tropaz max-w-screen-sm p-8 shadow-lg duration-300 hover:shadow-2xl'>
              <h2 className='my-4 text-xl'>RaspberryPi</h2>
                <div>
                  <p>自宅鯖のラズパイです</p>
                </div>
                <hr className='my-4' />
                <h2 className='my-2 text-xl'>Status</h2>
                {Activities2}
                <hr className='my-4' />
                <h2 className='my-2 text-xl'>温度</h2>
                {Activities3}℃ <br /><button className='mt-2 p-2 border-2' onClick={() => {getCo3().then(res => setActivities3(res))}}>更新</button>
              </div>
            </div>
      </main>
    </>
  )
}

//co1
const getCo1 = async () => {
  const ac = await (await fetch("/api/mi.skota11.com")).json();
  console.log(ac.main)
  return ac.main;
};
const getCo2 = async () => {
  const ac = await (await fetch("/api/ac.skota11.com-activities")).json();
  console.log(ac.main)
  return ac.main;
};
const getCo3 = async () => {
  const ac = await (await fetch("/api/temp.skota11.com")).json();
  console.log(ac.main)
  return ac.main;
};
